### ISSUE TITLE
Ошибка сериализации при отправке транзакции

### ISSUE THREAD

**Issue by draincoder** [alexveden/quik-lua-async-client-python#1]
Здравсвуйте, работал ли у вас метод `sendTransaction` c передачей в него транзакции в виде обычного словаря?
Пробовал по-разному кодировать-декодировать, но все тщетно.
Пример: 
```python3
transaction = {
                "TRANS_ID": "454264161",
                "ACTION": "NEW_ORDER",
                "CLASSCODE": "TQBR",
                "SECCODE": "LKOH",
                "OPERATION": "S",
                "TYPE": "M",
                "QUANTITY": "1",
                "FIRM_ID": "EXAMPLE",
                "PRICE": "0"
            }
await self.client.rpc_call('sendTransaction', transaction=transaction)
```
на что получаю ошибку `'utf-8' codec can't decode byte 0xcd in position 22: invalid continuation byte`.

В issues самого quik-lua-rpc были такие проблемы, но решение на других языках, либо не очевидно.
Спасибо за любую помощь.

**Comment by alexveden** [comment]
Добрый день, скиньте полный traceback ошибки, я посмотрю на днях.

**Comment by draincoder** [comment]
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\quik_trader\app\trader\market.py", line 180, in send_order
    await self.client.rpc_call('sendTransaction', transaction=transaction)
  File "C:\Users\roman\PycharmProjects\quik_trader\aioquiklua\client.py", line 798, in rpc_call
    return await self.zmq_pool_rpc.rpc_call(rpc_func, **rpc_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\quik_trader\aioquiklua\socket_pool.py", line 79, in rpc_call
    is_success, result = await self._loop.run_in_executor(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\PycharmProjects\quik_trader\aioquiklua\socket_pool.py", line 51, in send_receive
    response = socket.recv_json()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\AppData\Local\pypoetry\Cache\virtualenvs\quik-trader-3XXH1NdB-py3.11\Lib\site-packages\zmq\sugar\socket.py", line 1018, in recv_json
    return self._deserialize(msg, lambda buf: jsonapi.loads(buf, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\AppData\Local\pypoetry\Cache\virtualenvs\quik-trader-3XXH1NdB-py3.11\Lib\site-packages\zmq\sugar\socket.py", line 834, in _deserialize
    return load(recvd)
           ^^^^^^^^^^^
  File "C:\Users\roman\AppData\Local\pypoetry\Cache\virtualenvs\quik-trader-3XXH1NdB-py3.11\Lib\site-packages\zmq\sugar\socket.py", line 1018, in <lambda>
    return self._deserialize(msg, lambda buf: jsonapi.loads(buf, **kwargs))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roman\AppData\Local\pypoetry\Cache\virtualenvs\quik-trader-3XXH1NdB-py3.11\Lib\site-packages\zmq\utils\jsonapi.py", line 33, in loads
    s = s.decode("utf8")
        ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 22: invalid continuation byte

**Comment by draincoder** [comment]
А оно в принципе работало? Не было таких проблем на стороне pyzmq? Уже весь проект написал, и тут такая подстава)

**Comment by alexveden** [comment]
Я думаю я разобрался в проблеме, эта либа работает у меня ежедневно с 2021 года, единственный нюанс в том, что я использую английскую версию квика (проблемы с кодировкой под linux / wine). Квик скорее всего шлет все данные в кодировке cp1251, а питон пытаясь сконвертить ее в utf8 падает.

Вот пример
![image](https://github.com/alexveden/quik-lua-async-client-python/assets/18488560/56148de8-72d3-471d-bfe3-911cf543b22a)


Ваш код должен работать, я залил новый коммит, где этот баг должен быть исправлен. Дайте знать если помогло.

**Comment by draincoder** [comment]
Да, проблема с транзакцией решилась, но некоторые другие ответы, которые корректно декодировались с utf-8 , поплыли: `'tradingstatus': 'РѕС‚РєСЂС‹С‚Р°'`.
Мне кажется там надо сделать что-то вроде:
```python3
response_bytes = socket.recv(0)
try:
    response = json.loads(response_bytes.decode('utf-8'))
except UnicodeDecodeError:
    response = json.loads(response_bytes.decode('cp1251'))
```
Спасибо за помощь!

P.S. у меня есть еще некоторые вопросы по библиотеке, котрые не требуют issue, как я могу с вами связаться?

**Comment by alexveden** [comment]
Добавил ваш патч.
 
> P.S. у меня есть еще некоторые вопросы по библиотеке, котрые не требуют issue, как я могу с вами связаться?

Общие вопросы по либе пишите в issue, может быть кому-то еще будет полезно.
