### ISSUE TITLE
ZMQ TCP-соединение

### ISSUE THREAD

**Issue by draincoder** [alexveden/quik-lua-async-client-python#2]
В `client.py` имеется строчка `assert '127.0.0.1' in rpc_host or 'localhost' in rpc_host, f'Only localhost is allowed for RPC requests for security reasons, got {rpc_host}'`, которая запрещает соединяться с quik-lua-rpc не по локалхосту. Какими именно проблемами с безопасностью это может обернуться и что делать, если мне очень надо запустить quik + quik-lua-rpc на одной машине, а управлять всем этим с другой? Конечно, можно написать какое-нибудь REST API под https, но интересует вопрос подключения напрямую.

**Comment by alexveden** [comment]
Можно удалить этот assert, в принципе, в quik lua rpc / zmq есть механизмы авторизации через ключи/пароли, но я это не пробовал. На сколько помню авторизации в quik-lua-async-client-python нет.

Как альтернатива у меня есть другой проект на котором базируется моя инфраструктура: https://github.com/alexveden/yauber-executor. Там есть поддержка событий и аналога RPC, работает тоже на asyncio + rabbitmq.

**Comment by alexveden** [comment]
Удалил assert

**Comment by draincoder** [comment]
Спасибо, я тогда попробую все это дело настроить, PR приветствуются?

**Comment by alexveden** [comment]
Конечно PR приветствуются
