### ISSUE TITLE
Добавить библиотеку на PiPy

### ISSUE THREAD

**Issue by draincoder** [alexveden/quik-lua-async-client-python#4]
Возможно ли добавить библиотеку на PiPy?
Было бы очень удобно, готов заняться данным вопросом после проведения более глобального рефакторинга.

**Comment by alexveden** [comment]
Будет отлично.

**Comment by draincoder** [comment]
Поскольку библиотека ваша, то вам нужно будет через свой профиль PiPy ее заливать, я лишь подготовлю poetry окружение и составлю инструкцию.

**Comment by alexveden** [comment]
Хорошо, сделаю
